tests get questions by category name
leoni-q/stromwise pull request #12
Opened 2020-10-14 22:06 UTC by urbaniakmichal

2020-10-15 20:14 UTC, leoni-q requested changes

2020-10-15 20:14 UTC, leoni-q commented on backend/src/main/java/com/stromwise/skilltree/configuration/SwaggerConfig.java
> +                .title("Strommwise")
👍

2020-10-15 20:14 UTC, leoni-q commented on backend/src/main/java/com/stromwise/skilltree/question/GetQuestionService.java
> +    Set<Question> getQuestionsBelongToSpecificCategory(String categoriesName) {
how about ```getQuestionByCategory(String categoryName)``` ?

2020-10-15 20:14 UTC, leoni-q commented on backend/src/main/java/com/stromwise/skilltree/question/QuestionController.java
> +    @ApiOperation(value = "Get max to ten random questions belong to specific category")
Get random questions belonging to given category with limit defined by questionResultLimit property

2020-10-15 20:14 UTC, leoni-q commented on backend/src/main/java/com/stromwise/skilltree/question/QuestionController.java
> +    public ResponseEntity<Set<Question>> getQuestionsSimplified(@PathVariable("categoryName") String categoryName) {
When PathVariable name is the same as variable name you can simplify it to ```(@PathVariable String categoryName)```

2020-10-15 20:14 UTC, leoni-q commented on backend/src/main/java/com/stromwise/skilltree/question/QuestionRepository.java
> +    Set<Question> findRandomQuestionsBelongToSpecificCategory(String categoryName, String questionsResultLimit);
how about ```findRandomByCategoryName``` ?

2020-10-15 20:14 UTC, leoni-q commented on backend/src/test/java/com/stromwise/skilltree/question/GetQuestionServiceIntegrationTest.java
> +    public void clearData() {
it's common practice to name @before method as setup()

2020-10-15 20:14 UTC, leoni-q commented on backend/src/test/java/com/stromwise/skilltree/question/GetQuestionServiceIntegrationTest.java
> +        assertThat(questionRepository.findAll()).hasSize(0);
I think we can remove this asserts

2020-10-15 20:14 UTC, leoni-q commented on backend/src/test/java/com/stromwise/skilltree/question/GetQuestionServiceIntegrationTest.java
> +    @Transactional
Instead of giving @Transactional on every method can we give it on class itself?

2020-10-15 20:14 UTC, leoni-q commented on backend/src/test/java/com/stromwise/skilltree/question/GetQuestionServiceIntegrationTest.java
> +    public void should_get_nine_questions_of_four_with_limit_of_ten() {
why nine of four?

2020-10-15 20:14 UTC, leoni-q commented on backend/src/test/java/com/stromwise/skilltree/question/GetQuestionServiceIntegrationTest.java
> +    private boolean areQuestionsSorted(Set<Question> questions) {
IMO it's not deterministic, sometimes questions can be randomly returned in natural order

2020-10-15 20:14 UTC, leoni-q commented on backend/src/test/java/com/stromwise/skilltree/question/GetQuestionServiceTest.java
> +        assertThat(questionRepository.findRandomQuestionsBelongToSpecificCategory("programming", questionsResultLimit).size()).isEqualTo(questionSet.size());
asserts should not be placed in ```given``` part, to remove

2020-10-15 20:14 UTC, leoni-q commented on backend/src/test/java/com/stromwise/skilltree/question/QuestionControllerTest.java
> +        assertThat(questionRepository.findRandomQuestionsBelongToSpecificCategory("programming", questionsResultLimit).size()).isEqualTo(questionSet.size());
remove assert

2020-10-15 20:14 UTC, leoni-q commented on backend/src/test/java/com/stromwise/skilltree/question/QuestionControllerTest.java
> +                        .param("categoryName", "programming")
param not needed

2020-10-15 20:20 UTC, leoni-q commented on backend/src/main/java/com/stromwise/skilltree/question/QuestionController.java
> +        Set<Question> questionSet = getQuestionService.getQuestionsBelongToSpecificCategory(categoryName);
we should return some object, which contains set of simplified questions (only with publicId, question, answer), not whole db entity with categories, etc.

2020-10-16 14:16 UTC, urbaniakmichal commented on backend/src/test/java/com/stromwise/skilltree/question/GetQuestionServiceIntegrationTest.java
> +    private boolean areQuestionsSorted(Set<Question> questions) {
because its random. random is random.

2020-10-16 16:44 UTC, urbaniakmichal commented on backend/src/test/java/com/stromwise/skilltree/question/GetQuestionServiceIntegrationTest.java
> +    private boolean areQuestionsSorted(Set<Question> questions) {
ok i removed

2020-10-17 19:24 UTC, leoni-q requested changes

2020-10-17 19:24 UTC, leoni-q commented on backend/src/test/java/com/stromwise/skilltree/question/GetQuestionServiceTest.java
> +        verify(questionRepository, times(1)).findRandomByCategoryName("programming", questionsResultLimit);
times(1) is redundant, remove it

2020-10-17 19:24 UTC, leoni-q commented on backend/src/test/java/com/stromwise/skilltree/question/QuestionControllerTest.java
> +    @InjectMocks
injectMocks? Question converter has no dependencies

2020-10-17 19:24 UTC, leoni-q commented on backend/src/test/java/com/stromwise/skilltree/utils/QuestionConverterTest.java
> +    public void should_work_question_converter() {
should_convert_entities_to_payloads

2020-10-17 19:24 UTC, leoni-q commented on backend/src/main/java/com/stromwise/skilltree/utils/QuestionConverter.java
> +                .map(questionPojo -> new QuestionPayload(questionPojo.getPublicId(), questionPojo.getAnswer(), questionPojo.getQuestion()))
why questionPojo? It's questionEntity. And you put answer to question and question to answer :( Maybe we should use builder to avoid mistakes like this? And we shoud definitly include asserting this in test

2020-10-17 19:24 UTC, leoni-q commented on backend/src/main/java/com/stromwise/skilltree/utils/QuestionConverter.java
> +public class QuestionConverter {
why this class is in utils? I'd rather see it in question package, It's implementation detail of GetQuestionService, not something commonly used in the app

2020-10-17 19:24 UTC, leoni-q commented on backend/src/main/java/com/stromwise/skilltree/question/QuestionPayload.java
> +@Data
I think @Data is redundant and we can remove it

2020-10-17 19:24 UTC, leoni-q commented on backend/src/test/java/com/stromwise/skilltree/question/GetQuestionServiceIntegrationTest.java
> +    public void clearData() {
Now when I look on it I think it should be in @AfterEach

2020-10-18 10:59 UTC, urbaniakmichal commented on backend/src/test/java/com/stromwise/skilltree/question/GetQuestionServiceIntegrationTest.java
> +    @Transactional
good idea, I forgot about this trick

2020-10-18 11:03 UTC, urbaniakmichal commented on backend/src/main/java/com/stromwise/skilltree/utils/QuestionConverter.java
> +public class QuestionConverter {
hmm, sound good

2020-10-18 11:17 UTC, urbaniakmichal commented on backend/src/test/java/com/stromwise/skilltree/question/QuestionControllerTest.java
> +    @InjectMocks
right, I red about this

2020-10-18 11:27 UTC, urbaniakmichal commented on backend/src/main/java/com/stromwise/skilltree/utils/QuestionConverter.java
> +                .map(questionPojo -> new QuestionPayload(questionPojo.getPublicId(), questionPojo.getAnswer(), questionPojo.getQuestion()))
I agree, rename pojo and add builder are better ideas

2020-10-18 15:55 UTC, leoni-q approved these changes

2020-10-18 16:14 UTC, leoni-q approved these changes

2020-10-18 16:16 UTC, merged