Feature/frontend/sign email success
leoni-q/stromwise pull request #5
Opened 2020-09-04 16:46 UTC by urbaniakmichal

2020-09-06 17:08 UTC, leoni-q requested changes

2020-09-06 17:08 UTC, leoni-q commented on frontend/src/app/app-contact/contact-form/contact-form.component.ts
> +        <div>
remove it

2020-09-06 17:08 UTC, leoni-q commented on frontend/src/app/app-contact/contact-form/contact-form.service.ts
> +        () => {
1. Thanks for your email :)
2. remove console.log
3. There is a problem with sending your email

2020-09-06 17:08 UTC, leoni-q commented on frontend/src/app/utils/notification/notification.service.ts
> +    public snackBar: MatSnackBar, private zone: NgZone) { }
can snackBar be private?

2020-09-06 17:08 UTC, leoni-q commented on frontend/src/app/utils/errors/globalErrorHandler.ts
> +export class GlobalErrorHandler implements ErrorHandler {
change file name to global-error-handler.ts

2020-09-06 17:08 UTC, leoni-q commented on frontend/src/app/utils/logging/consoleLogging.service.ts
> +export class ConsoleLoggingService {
is this necessary? We actually log error to console in globalErrorHandler

2020-09-06 19:41 UTC, urbaniakmichal commented on frontend/src/app/utils/logging/consoleLogging.service.ts
> +export class ConsoleLoggingService {
hmmm its nice look xd

2020-09-06 20:10 UTC, urbaniakmichal commented on frontend/src/app/app.module.ts
> +import {NotificationComponent} from './utils/notification/notification.component';
notification.component is not exist so i removed it line

2020-09-07 18:03 UTC, leoni-q approved these changes

2020-09-09 14:03 UTC, merged